In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import time  

train_data= pd.read_excel("CLL788_A1/q2train.xlsx")

train_data.head() 

Aptitude     Verbal  Label
0  34.723660  30.386711      0
1  30.386711  35.947409      0
2  35.947409  60.282599      0
3  45.183277  61.206665      0
4  95.961555  75.113658      0

In [2]:
train_data.insert(loc=0, column='intercept', value=1.0)
d=train_data.to_numpy()
X=d[:,0:3]
Y=d[:,-1]

In [3]:
#Sigmoid Function
def sigmoid(x):
    z = 1/(1 + np.exp(-x))
    return z

In [4]:
#Batch LMS GRADIENT DESCENT
start_time = time.time()
alpha = 0.001 
tol=1e-4
m = Y.size 
weights = np.array([np.random.random(1)[0],np.random.random(1)[0],np.random.random(1)[0]])
cost=0
prev_cost=99999
cost_hist=[]
while(abs(cost-prev_cost)>tol):
    pred = sigmoid(X.dot(weights))
    prev_cost = np.sum((pred-Y)**2)/(2*m)
    weights = weights - alpha*(X.T.dot(pred-Y))/m
    cost = Y.dot(np.log(pred))+(1-Y).dot(np.log(1-np.log(pred)))
    cost_hist.append(cost)
print("Convergence Time:", (time.time() - start_time)) 
print(weights)

Convergence Time: 0.18726754188537598
[ 0.0466419   0.02988976 -0.02543308]


In [5]:
ypred=sigmoid(X.dot(weights))
ypred = np.where(ypred > 0.5, 1, 0)       

In [6]:
ypred

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1])

In [7]:
#Training Accuracy
ct = 0    
correctly_classified=0
for ct in range(np.size(ypred)):  
    if (Y[ct] == ypred[ct]) :            
        correctly_classified = correctly_classified + 1       
          
print( "Accuracy on training set:", ( correctly_classified / ct ) * 100,"%")

Accuracy on training set: 68.11594202898551 %


In [14]:
#Prediction on test data
test_data= pd.read_excel("CLL788_A1/q2test.xlsx")
print(test_data.head()) 
test_data.insert(loc=0, column='intercept', value=1.0)
d=test_data.to_numpy()
X_test=d[:,0:3]
# print(X_test)

    Aptitude     Verbal
0  32.822833  43.407173
1  64.139320  78.131688
2  72.446494  96.327593
3  60.557886  73.194998
4  58.940956  75.958448


In [15]:
ypred_test=sigmoid(X_test.dot(weights))
ypred_test = np.where(ypred_test > 0.5, 1, 0 ) 

In [16]:
ypred_test

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1])

In [11]:
ypred_test.shape

(70,)

In [32]:
np.savetxt('output1.txt', ypred_test, fmt ='%.0f\n')